### ISSUE TITLE
Updating between CI built apks doesnt work

### ISSUE THREAD

**Issue by lxea** [paroj/DSub2000#22]
When I try to update the dsub2000 install between CI artifact builds it says there is a conflicting app already installed.

Maybe it needs to build using the same signature?

**Comment by norohind** [comment]
Hello. Now CI pipeline produces signed with already present in repo debug key. It allows to upgrade the application from CI artifacts and should allow you to sign an apk by yourself (for example, if you want to play around with custom modifications). 

Just don't install Dsub from untrusted sources because anybody can use this key to sign anything.
